### ISSUE TITLE
jumpserver web终端不能登录主机，docker-compose日志输入ERROR: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header.

### ISSUE THREAD

**Issue by huliangfei** [wojiushixiaobai/docker-compose#2]
**[简述你的问题]**
jumpserver web终端不能登录，docker-compose日志输入ERROR: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header.

**使用版本**
Jumpserver: 1.5.4
OS: CentOS Linux release 7.6.1810 (Core)
Docker : 19.03.4
镜像：使用wojiushixiaobai项目镜像

**问题复现步骤**
[步骤1]
[步骤2]

[注:] 完成后请关闭 issue

**解决方法**
需在Nginx镜像的nginx.conf文件，koko项中，增加
        location /koko/ {
            proxy_pass       http://koko:5000;
            **proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;**

**Comment by wojiushixiaobai** [comment]
@huliangfei 感谢反馈，确实少了三行，疏忽了。
已经修复，稍后单独更新一下nginx镜像即可
