### ISSUE TITLE
任务列表  成功状态无法显示

### ISSUE THREAD

**Issue by r6c** [wojiushixiaobai/docker-compose#3]
![image](https://user-images.githubusercontent.com/45527749/68523633-afa11000-02f6-11ea-9181-95b4af65ed0b.png)
![image](https://user-images.githubusercontent.com/45527749/68523637-bcbdff00-02f6-11ea-9df7-48e47776e3c5.png)

**Comment by r6c** [comment]
![image](https://user-images.githubusercontent.com/45527749/68523647-d7907380-02f6-11ea-8eff-9b768ae07968.png)
点击 执行 是能执行成功的

**Comment by wojiushixiaobai** [comment]
@r6c 这个可能是第一次执行失败了，这个不影响使用的话忽略吧，状态会在之后更新的。
