### ISSUE TITLE
nginx的域名证书问题

### ISSUE THREAD

**Issue by xiaomao361** [wojiushixiaobai/docker-compose#4]
我看了下配置和.env这些文件，暂时是不支持添加域名证书以支持https的对吧？
如果我需要的话，是不是需要修改nginx.conf和nginx下的Dockerfile然后重新构建下？

**Comment by wojiushixiaobai** [comment]
@xiaomao361 没必要呀，你前面在加一层nginx反向代理即可。

**Comment by xiaomao361** [comment]
也可以哈...就是 nginx+nginx 怪怪的哈哈，谢谢啦。

**Comment by wojiushixiaobai** [comment]
@xiaomao361 企业对外的话，前端一般都有其他的代理服务器，所以暂时就没做这方面的处理，如果你确实需要的话，可以部署后直接到容器里面改下设置就好。分发的话建议重新构建下镜像。

**Comment by xiaomao361** [comment]
明白，多谢。
