### ISSUE TITLE
jumpserver的组件支持多副本运行吗？

### ISSUE THREAD

**Issue by TimeBye** [wojiushixiaobai/docker-compose#5]
你好，请问一下组件可以同时运行多个副本以达到高可用的目的吗？
- jms_core
- jms_koko
- jms_guacamole

比如执行：
```
# 将 jms_core 运行三个副本
 docker-compose scale core=3
```

**Comment by wojiushixiaobai** [comment]
@TimeBye 你应该用 jms_all 镜像，设置好数据库的配置，然后启动多个副本即可
